"""Add price

Revision ID: 57642bbc5015
Revises: 6b66b7cc2f1f
Create Date: 2021-11-18 17:58:58.263480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57642bbc5015'
down_revision = '6b66b7cc2f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'price')
    # ### end Alembic commands ###
