"""fixing db

Revision ID: 6b66b7cc2f1f
Revises: 
Create Date: 2021-11-12 20:44:35.724703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b66b7cc2f1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    op.drop_column('post', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('price', sa.INTEGER(), nullable=False))
    op.add_column('post', sa.Column('image', sa.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###
